spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level.org.springframework.web: INFO

packager:
  batch-size: 5
  timeout: PT30M
  remote-api-url: http://example.com/api/metadata
  token-url: http://example.com/oauth/token
  client-id: myClient
  client-secret: mySecret
  master-key: 0123456789abcdef0123456789abcdef
